name = "PFVG_AA2021"
uuid = "593bb313-7fc8-446a-96f6-bb1e55a541c0"
authors = ["ngiann <ngiann@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
